# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EuropeanVatRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, verbose_name='country code')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='data')),
            ],
        ),
    ]
