# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_prices_vatlayer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vat',
            new_name='EuropeanVatRates',
        ),
    ]
