# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_prices_vatlayer', '0002_auto_20170120_1019'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EuropeanVatRates',
            new_name='EuropeanVatRate',
        ),
    ]
